Support url parsing at compile-time via proc-macro
servo/rust-url pull request #951
Opened 2024-07-09 15:22 UTC by NobodyXu

Added new crate `url_macro`, usage:

```rust
const URL: url::Url = url_macro::parse!("https://www.github.com");
assert_eq!(URL, url::Url::parse("https://www.github.com").unwrap());
```

2024-07-09 15:27 UTC, NobodyXu commented on url/src/lib.rs
> +    serialization: Cow<'static, str>,
Could replace this with [`beef::lean::Cow`](https://docs.rs/beef/latest/beef/lean/type.Cow.html) to reduce size of `Url`, but might be a pre-mature optimization

2024-07-09 15:30 UTC, NobodyXu commented on url-macro/src/lib.rs
> +pub fn parse(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
TODO: Add test for `parse!`

2024-07-09 15:31 UTC, Manishearth requested changes
I'm not convinced this is worth the addition of the Cow, or worth it for _this_ project to maintain

2024-07-13 08:27 UTC, closed without merging

2024-07-13 08:27 UTC, NobodyXu commented
Thanks for the quick feedback, in that case I will close this.